public enum TokenType {
    SELECT, INSERT, DELETE, FROM, WHERE, VALUES, INTO, ORDER, GROUP, BY,
    IDENTIFIER, NUMBER, STRING, EQUALS, GREATER, LESS, AND, OR, NOT, COMMA,
    LPAREN, RPAREN, SEMICOLON,STAR, ASC, DESC, END, UNKNOWN, IS, NULL;
}
